{"timestamp": "2025-09-11T15:56:27.413955", "error_type": "ai_generation_exception", "question": "Average processing time by region", "generated_sql": "", "error_message": "None", "additional_context": {"error_details": {"type": "ai_generation_exception", "exception_type": "KeyError", "exception_message": "None", "question": "Average processing time by region", "timestamp": "2025-09-11 15:56:27"}, "timestamp": "2025-09-11 15:56:27"}}
{"timestamp": "2025-09-11T15:57:01.934539", "error_type": "ai_generation_exception", "question": "How are our customers distributed by segment?", "generated_sql": "", "error_message": "None", "additional_context": {"error_details": {"type": "ai_generation_exception", "exception_type": "KeyError", "exception_message": "None", "question": "How are our customers distributed by segment?", "timestamp": "2025-09-11 15:57:01"}, "timestamp": "2025-09-11 15:57:01"}}
{"timestamp": "2025-09-11T16:10:05.026146", "error_type": "ai_generation_exception", "question": "Average processing time by region", "generated_sql": "", "error_message": "None", "additional_context": {"error_details": {"type": "ai_generation_exception", "exception_type": "KeyError", "exception_message": "None", "question": "Average processing time by region", "timestamp": "2025-09-11 16:10:05"}, "timestamp": "2025-09-11 16:10:05"}}
{"timestamp": "2025-09-11T16:10:41.089051", "error_type": "ai_generation_exception", "question": "How are our customers distributed by segment?", "generated_sql": "", "error_message": "None", "additional_context": {"error_details": {"type": "ai_generation_exception", "exception_type": "KeyError", "exception_message": "None", "question": "How are our customers distributed by segment?", "timestamp": "2025-09-11 16:10:41"}, "timestamp": "2025-09-11 16:10:41"}}
{"timestamp": "2025-09-11T16:26:59.743541", "error_type": "ai_generation_exception", "question": "Show me data from a non-existent table called 'fake_table'", "generated_sql": "", "error_message": "(pymysql.err.ProgrammingError) (1146, \"Table 'sales.fake_table' doesn't exist\")\n[SQL: SELECT * FROM fake_table;]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "additional_context": {"error_details": {"type": "sql_execution_error", "exception_type": "ProgrammingError", "exception_message": "(pymysql.err.ProgrammingError) (1146, \"Table 'sales.fake_table' doesn't exist\")\n[SQL: SELECT * FROM fake_table;]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "sql_attempted": "SELECT * FROM fake_table;", "timestamp": "2025-09-11 16:26:59", "question": "Show me data from a non-existent table called 'fake_table'"}, "timestamp": "2025-09-11 16:26:59"}}
{"timestamp": "2025-09-11T16:33:15.515950", "error_type": "ai_generation_exception", "question": "Show me data from a non-existent table called 'fake_table'", "generated_sql": "", "error_message": "(pymysql.err.ProgrammingError) (1146, \"Table 'sales.fake_table' doesn't exist\")\n[SQL: SELECT * FROM fake_table;]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "additional_context": {"error_details": {"type": "sql_execution_error", "exception_type": "ProgrammingError", "exception_message": "(pymysql.err.ProgrammingError) (1146, \"Table 'sales.fake_table' doesn't exist\")\n[SQL: SELECT * FROM fake_table;]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "sql_attempted": "SELECT * FROM fake_table;", "timestamp": "2025-09-11 16:33:15", "question": "Show me data from a non-existent table called 'fake_table'"}, "timestamp": "2025-09-11 16:33:15"}}
